services:
  mongodb:
    image: 'mongo:7.0'
    container_name: catalogo-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo_data:/data/db

  redis:
    image: 'redis:7.2-alpine'
    container_name: catalogo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: